---
title: "CP3"
author: "Ledia Dobi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## library chunk
# First, install any packages that are not already installed
```{r libraries, include=FALSE}
required_packages <- c("dplyr", "readr", "tidyverse", "lmtest", "lubridate", "glmnet", "pls", "readxl", "GGally", "boot", "scales", "ggthemes", "caret")
install.packages(setdiff(required_packages, rownames(installed.packages())))
```

# Second, load all the packages
```{r load, include=FALSE}
invisible(lapply(required_packages, library, character.only = TRUE))
```

# Import Datasets
```{r import datasets, include=FALSE}
beauty <- read.csv("Beauty Care.csv")
hair <- read.csv("Hair.csv")
household <- read.csv("Household Care.csv")
makeup <- read.csv("Makeup.csv")
pet <- read.csv("Pet Care.csv")
skincare <- read.csv("Skincare.csv")
```

# View Datasets to see what we need to clean up before we combine
```{r view, include=FALSE}
view(beauty)
view(hair)
view(household)
view(makeup)
view(pet)
view(skincare)
```